# netlify.toml

[build]
  # Directory to run the build command in (usually the root of your project)
  base = "."

  # Command to build your site (e.g., for a create-react-app project)
  command = "npm run build"

  # Directory with the build output (e.g., the build folder for create-react-app)
  publish = "build"

  # Directory containing your serverless functions
  functions = "functions"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
